<?php

/**
 * This is the model base class for the table "shop_order".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "ShopOrderModel".
 *
 * Columns in table "shop_order" available as properties of the model,
 * and there are no model relations.
 *
 * @property integer $order_id
 * @property integer $customer_id
 * @property integer $delivery_address_id
 * @property integer $billing_address_id
 * @property integer $ordering_date
 * @property integer $ordering_done
 * @property integer $ordering_confirmed
 * @property integer $payment_method
 * @property integer $shipping_method
 * @property string $comment
 *
 */
abstract class BaseShopOrderModel extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'shop_order';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'ShopOrderModel|ShopOrderModels', $n);
	}

	public static function representingColumn() {
		return 'comment';
	}

	public function rules() {
		return array(
			array('customer_id, delivery_address_id, billing_address_id, ordering_date, payment_method, shipping_method', 'required'),
			array('customer_id, delivery_address_id, billing_address_id, ordering_date, ordering_done, ordering_confirmed, payment_method, shipping_method', 'numerical', 'integerOnly'=>true),
			array('comment', 'safe'),
			array('ordering_done, ordering_confirmed, comment', 'default', 'setOnEmpty' => true, 'value' => null),
			array('order_id, customer_id, delivery_address_id, billing_address_id, ordering_date, ordering_done, ordering_confirmed, payment_method, shipping_method, comment', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'order_id' => Yii::t('app', 'Order'),
			'customer_id' => null,
			'delivery_address_id' => Yii::t('app', 'Delivery Address'),
			'billing_address_id' => Yii::t('app', 'Billing Address'),
			'ordering_date' => Yii::t('app', 'Ordering Date'),
			'ordering_done' => Yii::t('app', 'Ordering Done'),
			'ordering_confirmed' => Yii::t('app', 'Ordering Confirmed'),
			'payment_method' => Yii::t('app', 'Payment Method'),
			'shipping_method' => Yii::t('app', 'Shipping Method'),
			'comment' => Yii::t('app', 'Comment'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('order_id', $this->order_id);
		$criteria->compare('customer_id', $this->customer_id);
		$criteria->compare('delivery_address_id', $this->delivery_address_id);
		$criteria->compare('billing_address_id', $this->billing_address_id);
		$criteria->compare('ordering_date', $this->ordering_date);
		$criteria->compare('ordering_done', $this->ordering_done);
		$criteria->compare('ordering_confirmed', $this->ordering_confirmed);
		$criteria->compare('payment_method', $this->payment_method);
		$criteria->compare('shipping_method', $this->shipping_method);
		$criteria->compare('comment', $this->comment, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}