<?php

/**
 * This is the model base class for the table "poll_choice".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "PollChoiceModel".
 *
 * Columns in table "poll_choice" available as properties of the model,
 * and there are no model relations.
 *
 * @property string $id
 * @property string $poll_id
 * @property string $label
 * @property string $votes
 * @property integer $weight
 *
 */
abstract class BasePollChoiceModel extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'poll_choice';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'PollChoiceModel|PollChoiceModels', $n);
	}

	public static function representingColumn() {
		return 'label';
	}

	public function rules() {
		return array(
			array('poll_id', 'required'),
			array('weight', 'numerical', 'integerOnly'=>true),
			array('poll_id, votes', 'length', 'max'=>11),
			array('label', 'length', 'max'=>255),
			array('label, votes, weight', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, poll_id, label, votes, weight', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'poll_id' => null,
			'label' => Yii::t('app', 'Label'),
			'votes' => Yii::t('app', 'Votes'),
			'weight' => Yii::t('app', 'Weight'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id, true);
		$criteria->compare('poll_id', $this->poll_id);
		$criteria->compare('label', $this->label, true);
		$criteria->compare('votes', $this->votes, true);
		$criteria->compare('weight', $this->weight);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}