<?php

/**
 * This is the model base class for the table "shop_order_transaction".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "ShopOrderTransactionModel".
 *
 * Columns in table "shop_order_transaction" available as properties of the model,
 * and there are no model relations.
 *
 * @property integer $id
 * @property string $username
 * @property string $phone
 * @property string $ship_address
 * @property integer $payment_method
 * @property integer $ship_method
 * @property integer $user_id
 * @property string $cart
 * @property integer $status
 * @property string $created_datetime
 *
 */
abstract class BaseShopOrderTransactionModel extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'shop_order_transaction';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'ShopOrderTransactionModel|ShopOrderTransactionModels', $n);
	}

	public static function representingColumn() {
		return 'username';
	}

	public function rules() {
		return array(
			array('username, phone, ship_address', 'required'),
			array('payment_method, ship_method, user_id, status', 'numerical', 'integerOnly'=>true),
			array('username', 'length', 'max'=>255),
			array('phone', 'length', 'max'=>100),
			array('cart, created_datetime', 'safe'),
			array('payment_method, ship_method, user_id, cart, status, created_datetime', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, username, phone, ship_address, payment_method, ship_method, user_id, cart, status, created_datetime', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'username' => Yii::t('app', 'Username'),
			'phone' => Yii::t('app', 'Phone'),
			'ship_address' => Yii::t('app', 'Ship Address'),
			'payment_method' => Yii::t('app', 'Payment Method'),
			'ship_method' => Yii::t('app', 'Ship Method'),
			'user_id' => Yii::t('app', 'User'),
			'cart' => Yii::t('app', 'Cart'),
			'status' => Yii::t('app', 'Status'),
			'created_datetime' => Yii::t('app', 'Created Datetime'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('username', $this->username, true);
		$criteria->compare('phone', $this->phone, true);
		$criteria->compare('ship_address', $this->ship_address, true);
		$criteria->compare('payment_method', $this->payment_method);
		$criteria->compare('ship_method', $this->ship_method);
		$criteria->compare('user_id', $this->user_id);
		$criteria->compare('cart', $this->cart, true);
		$criteria->compare('status', $this->status);
		$criteria->compare('created_datetime', $this->created_datetime, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}