<?php

/**
 * This is the model base class for the table "{{system_settings}}".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "SystemSettingsModel".
 *
 * Columns in table "{{system_settings}}" available as properties of the model,
 * and there are no model relations.
 *
 * @property integer $id
 * @property string $name
 * @property string $description
 * @property string $email
 * @property integer $paging
 * @property string $address
 *
 */
abstract class BaseSystemSettingsModel extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return '{{system_settings}}';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'SystemSettingsModel|SystemSettingsModels', $n);
	}

	public static function representingColumn() {
		return 'name';
	}

	public function rules() {
		return array(
			array('name', 'required'),
			array('paging', 'numerical', 'integerOnly'=>true),
			array('name, email', 'length', 'max'=>255),
			array('description, address', 'safe'),
			array('description, email, paging, address', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, name, description, email, paging, address', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'name' => Yii::t('app', 'Name'),
			'description' => Yii::t('app', 'Description'),
			'email' => Yii::t('app', 'Email'),
			'paging' => Yii::t('app', 'Paging'),
			'address' => Yii::t('app', 'Address'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('name', $this->name, true);
		$criteria->compare('description', $this->description, true);
		$criteria->compare('email', $this->email, true);
		$criteria->compare('paging', $this->paging);
		$criteria->compare('address', $this->address, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}