<?php

/**
 * This is the model base class for the table "shop_manufactor".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "ShopManufactorModel".
 *
 * Columns in table "shop_manufactor" available as properties of the model,
 * and there are no model relations.
 *
 * @property integer $id
 * @property string $name
 * @property string $description
 * @property string $image
 * @property integer $position
 *
 */
abstract class BaseShopManufactorModel extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'shop_manufactor';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'ShopManufactorModel|ShopManufactorModels', $n);
	}

	public static function representingColumn() {
		return 'name';
	}

	public function rules() {
		return array(
			array('name', 'required'),
			array('position', 'numerical', 'integerOnly'=>true),
			array('name, image', 'length', 'max'=>255),
			array('description', 'safe'),
			array('description, image, position', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, name, description, image, position', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'name' => Yii::t('app', 'Name'),
			'description' => Yii::t('app', 'Description'),
			'image' => Yii::t('app', 'Image'),
			'position' => Yii::t('app', 'Position'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('name', $this->name, true);
		$criteria->compare('description', $this->description, true);
		$criteria->compare('image', $this->image, true);
		$criteria->compare('position', $this->position);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}