<?php

/**
 * This is the model base class for the table "{{ask}}".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "AskModel".
 *
 * Columns in table "{{ask}}" available as properties of the model,
 * and there are no model relations.
 *
 * @property integer $id
 * @property string $title
 * @property string $content
 * @property integer $cat_id
 * @property string $params
 * @property string $avatar
 * @property string $email
 * @property string $created_datetime
 * @property integer $published
 *
 */
abstract class BaseAskModel extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return '{{ask}}';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'AskModel|AskModels', $n);
	}

	public static function representingColumn() {
		return 'title';
	}

	public function rules() {
		return array(
			array('title, content, avatar, created_datetime', 'required'),
			array('cat_id, published', 'numerical', 'integerOnly'=>true),
			array('title, avatar, email', 'length', 'max'=>255),
			array('params', 'safe'),
			array('cat_id, params, email, published', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, title, content, cat_id, params, avatar, email, created_datetime, published', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'title' => Yii::t('app', 'Title'),
			'content' => Yii::t('app', 'Content'),
			'cat_id' => Yii::t('app', 'Cat'),
			'params' => Yii::t('app', 'Params'),
			'avatar' => Yii::t('app', 'Avatar'),
			'email' => Yii::t('app', 'Email'),
			'created_datetime' => Yii::t('app', 'Created Datetime'),
			'published' => Yii::t('app', 'Published'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('title', $this->title, true);
		$criteria->compare('content', $this->content, true);
		$criteria->compare('cat_id', $this->cat_id);
		$criteria->compare('params', $this->params, true);
		$criteria->compare('avatar', $this->avatar, true);
		$criteria->compare('email', $this->email, true);
		$criteria->compare('created_datetime', $this->created_datetime, true);
		$criteria->compare('published', $this->published);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}