<?php

/**
 * This is the model base class for the table "shop_order_position".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "ShopOrderPositionModel".
 *
 * Columns in table "shop_order_position" available as properties of the model,
 * and there are no model relations.
 *
 * @property integer $id
 * @property integer $order_id
 * @property integer $product_id
 * @property integer $amount
 * @property string $specifications
 *
 */
abstract class BaseShopOrderPositionModel extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'shop_order_position';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'ShopOrderPositionModel|ShopOrderPositionModels', $n);
	}

	public static function representingColumn() {
		return 'specifications';
	}

	public function rules() {
		return array(
			array('order_id, product_id, amount, specifications', 'required'),
			array('order_id, product_id, amount', 'numerical', 'integerOnly'=>true),
			array('id, order_id, product_id, amount, specifications', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'order_id' => Yii::t('app', 'Order'),
			'product_id' => Yii::t('app', 'Product'),
			'amount' => Yii::t('app', 'Amount'),
			'specifications' => Yii::t('app', 'Specifications'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('order_id', $this->order_id);
		$criteria->compare('product_id', $this->product_id);
		$criteria->compare('amount', $this->amount);
		$criteria->compare('specifications', $this->specifications, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}