<?php

/**
 * This is the model base class for the table "{{files}}".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "FilesModel".
 *
 * Columns in table "{{files}}" available as properties of the model,
 * and there are no model relations.
 *
 * @property integer $id
 * @property string $name
 * @property string $source_path
 * @property string $file_type
 * @property string $file_size
 * @property integer $download
 * @property integer $view
 * @property string $updated_datetime
 * @property string $created_datetime
 *
 */
abstract class BaseFilesModel extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return '{{files}}';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'FilesModel|FilesModels', $n);
	}

	public static function representingColumn() {
		return 'name';
	}

	public function rules() {
		return array(
			array('name', 'required'),
			array('download, view', 'numerical', 'integerOnly'=>true),
			array('name, source_path, file_size', 'length', 'max'=>255),
			array('file_type', 'length', 'max'=>100),
			array('updated_datetime, created_datetime', 'safe'),
			array('source_path, file_type, file_size, download, view, updated_datetime, created_datetime', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, name, source_path, file_type, file_size, download, view, updated_datetime, created_datetime', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'name' => Yii::t('app', 'Name'),
			'source_path' => Yii::t('app', 'File'),
			'file_type' => Yii::t('app', 'File Type'),
			'file_size' => Yii::t('app', 'File Size'),
			'download' => Yii::t('app', 'Download'),
			'view' => Yii::t('app', 'View'),
			'updated_datetime' => Yii::t('app', 'Updated Datetime'),
			'created_datetime' => Yii::t('app', 'Created Datetime'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('name', $this->name, true);
		$criteria->compare('source_path', $this->source_path, true);
		$criteria->compare('file_type', $this->file_type, true);
		$criteria->compare('file_size', $this->file_size, true);
		$criteria->compare('download', $this->download);
		$criteria->compare('view', $this->view);
		$criteria->compare('updated_datetime', $this->updated_datetime, true);
		$criteria->compare('created_datetime', $this->created_datetime, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}