<?php

/**
 * This is the model base class for the table "{{banners}}".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "BannersModel".
 *
 * Columns in table "{{banners}}" available as properties of the model,
 * and there are no model relations.
 *
 * @property integer $id
 * @property string $name
 * @property integer $client_id
 * @property integer $ordering
 * @property integer $clicks
 * @property string $content
 * @property integer $content_type
 * @property string $params
 * @property string $click_url
 * @property integer $published
 * @property string $created_time
 * @property string $update_time
 *
 */
abstract class BaseBannersModel extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return '{{banners}}';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'BannersModel|BannersModels', $n);
	}

	public static function representingColumn() {
		return 'name';
	}

	public function rules() {
		return array(
			array('name, created_time', 'required'),
			array('client_id, ordering, clicks, content_type, published', 'numerical', 'integerOnly'=>true),
			array('name, content, click_url', 'length', 'max'=>255),
			array('params, update_time', 'safe'),
			array('client_id, ordering, clicks, content, content_type, params, click_url, published, update_time', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, name, client_id, ordering, clicks, content, content_type, params, click_url, published, created_time, update_time', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'name' => Yii::t('app', 'Name'),
			'client_id' => Yii::t('app', 'Client'),
			'ordering' => Yii::t('app', 'Ordering'),
			'clicks' => Yii::t('app', 'Clicks'),
			'content' => Yii::t('app', 'Content'),
			'content_type' => Yii::t('app', 'Content Type'),
			'params' => Yii::t('app', 'Params'),
			'click_url' => Yii::t('app', 'Click Url'),
			'published' => Yii::t('app', 'Published'),
			'created_time' => Yii::t('app', 'Created Time'),
			'update_time' => Yii::t('app', 'Update Time'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('name', $this->name, true);
		$criteria->compare('client_id', $this->client_id);
		$criteria->compare('ordering', $this->ordering);
		$criteria->compare('clicks', $this->clicks);
		$criteria->compare('content', $this->content, true);
		$criteria->compare('content_type', $this->content_type);
		$criteria->compare('params', $this->params, true);
		$criteria->compare('click_url', $this->click_url, true);
		$criteria->compare('published', $this->published);
		$criteria->compare('created_time', $this->created_time, true);
		$criteria->compare('update_time', $this->update_time, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}