<?php

/**
 * This is the model base class for the table "{{banners_clients}}".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "BannersClientsModel".
 *
 * Columns in table "{{banners_clients}}" available as properties of the model,
 * and there are no model relations.
 *
 * @property integer $id
 * @property string $name
 * @property string $contact
 * @property string $email
 * @property integer $actived
 *
 */
abstract class BaseBannersClientsModel extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return '{{banners_clients}}';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'BannersClientsModel|BannersClientsModels', $n);
	}

	public static function representingColumn() {
		return 'name';
	}

	public function rules() {
		return array(
			array('name, email', 'required'),
			array('actived', 'numerical', 'integerOnly'=>true),
			array('name, email', 'length', 'max'=>255),
			array('contact', 'safe'),
			array('contact, actived', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, name, contact, email, actived', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'name' => Yii::t('app', 'Name'),
			'contact' => Yii::t('app', 'Contact'),
			'email' => Yii::t('app', 'Email'),
			'actived' => Yii::t('app', 'Actived'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('name', $this->name, true);
		$criteria->compare('contact', $this->contact, true);
		$criteria->compare('email', $this->email, true);
		$criteria->compare('actived', $this->actived);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}