<?php

/**
 * This is the model base class for the table "shop_product_category".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "ShopProductCategoryModel".
 *
 * Columns in table "shop_product_category" available as properties of the model,
 * and there are no model relations.
 *
 * @property integer $id
 * @property integer $category_id
 * @property integer $product_id
 * @property integer $type
 *
 */
abstract class BaseShopProductCategoryModel extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'shop_product_category';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'ShopProductCategoryModel|ShopProductCategoryModels', $n);
	}

	public static function representingColumn() {
		return 'id';
	}

	public function rules() {
		return array(
			array('category_id, product_id, type', 'numerical', 'integerOnly'=>true),
			array('category_id, product_id, type', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, category_id, product_id, type', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'category_id' => Yii::t('app', 'Category'),
			'product_id' => Yii::t('app', 'Product'),
			'type' => Yii::t('app', 'Type'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('category_id', $this->category_id);
		$criteria->compare('product_id', $this->product_id);
		$criteria->compare('type', $this->type);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}