<?php

/**
 * This is the model base class for the table "shop_shipping_method".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "ShopShippingMethodModel".
 *
 * Columns in table "shop_shipping_method" available as properties of the model,
 * and there are no model relations.
 *
 * @property string $id
 * @property string $title
 * @property string $description
 * @property integer $tax_id
 * @property double $price
 *
 */
abstract class BaseShopShippingMethodModel extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'shop_shipping_method';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'ShopShippingMethodModel|ShopShippingMethodModels', $n);
	}

	public static function representingColumn() {
		return 'title';
	}

	public function rules() {
		return array(
			array('title, tax_id, price', 'required'),
			array('tax_id', 'numerical', 'integerOnly'=>true),
			array('price', 'numerical'),
			array('title', 'length', 'max'=>255),
			array('description', 'safe'),
			array('description', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, title, description, tax_id, price', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'title' => Yii::t('app', 'Title'),
			'description' => Yii::t('app', 'Description'),
			'tax_id' => Yii::t('app', 'Tax'),
			'price' => Yii::t('app', 'Price'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id, true);
		$criteria->compare('title', $this->title, true);
		$criteria->compare('description', $this->description, true);
		$criteria->compare('tax_id', $this->tax_id);
		$criteria->compare('price', $this->price);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}