<?php

/**
 * This is the model base class for the table "shop_product_specification".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "ShopProductSpecificationModel".
 *
 * Columns in table "shop_product_specification" available as properties of the model,
 * and there are no model relations.
 *
 * @property integer $id
 * @property string $title
 * @property integer $is_user_input
 * @property integer $required
 *
 */
abstract class BaseShopProductSpecificationModel extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'shop_product_specification';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'ShopProductSpecificationModel|ShopProductSpecificationModels', $n);
	}

	public static function representingColumn() {
		return 'title';
	}

	public function rules() {
		return array(
			array('title', 'required'),
			array('is_user_input, required', 'numerical', 'integerOnly'=>true),
			array('title', 'length', 'max'=>255),
			array('is_user_input, required', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, title, is_user_input, required', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'title' => Yii::t('app', 'Title'),
			'is_user_input' => Yii::t('app', 'Is User Input'),
			'required' => Yii::t('app', 'Required'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('title', $this->title, true);
		$criteria->compare('is_user_input', $this->is_user_input);
		$criteria->compare('required', $this->required);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}