<?php

/**
 * This is the model base class for the table "{{categories}}".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "CategoriesModel".
 *
 * Columns in table "{{categories}}" available as properties of the model,
 * and there are no model relations.
 *
 * @property integer $id
 * @property integer $parent_id
 * @property integer $level
 * @property string $title
 * @property string $title_tree
 * @property string $alias
 * @property string $alias_en
 * @property string $description
 * @property integer $position
 * @property integer $ordering
 * @property string $language
 * @property string $translate_key
 * @property string $created
 * @property integer $created_by
 * @property string $modified
 * @property integer $modified_by
 * @property integer $published
 *
 */
abstract class BaseCategoriesModel extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'tbl_categories';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'CategoriesModel|CategoriesModels', $n);
	}

	public static function representingColumn() {
		return 'title';
	}

	public function rules() {
		return array(
			array('title, alias', 'required'),
			array('parent_id, level, position, ordering, created_by, modified_by, published', 'numerical', 'integerOnly'=>true),
			array('title, title_tree, alias, alias_en, translate_key', 'length', 'max'=>255),
			array('language', 'length', 'max'=>10),
			array('description, created, modified', 'safe'),
			array('parent_id, level, title_tree, alias_en, description, position, ordering, language, translate_key, created, created_by, modified, modified_by, published', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, parent_id, level, title, title_tree, alias, alias_en, description, position, ordering, language, translate_key, created, created_by, modified, modified_by, published', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'parent_id' => Yii::t('app', 'Parent'),
			'level' => Yii::t('app', 'Level'),
			'title' => Yii::t('app', 'Title'),
			'title_tree' => Yii::t('app', 'Title Tree'),
			'alias' => Yii::t('app', 'Alias'),
			'alias_en' => Yii::t('app', 'Alias En'),
			'description' => Yii::t('app', 'Description'),
			'position' => Yii::t('app', 'Position'),
			'ordering' => Yii::t('app', 'Ordering'),
			'language' => Yii::t('app', 'Language'),
			'translate_key' => Yii::t('app', 'Translate Key'),
			'created' => Yii::t('app', 'Created'),
			'created_by' => Yii::t('app', 'Created By'),
			'modified' => Yii::t('app', 'Modified'),
			'modified_by' => Yii::t('app', 'Modified By'),
			'published' => Yii::t('app', 'Published'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('parent_id', $this->parent_id);
		$criteria->compare('level', $this->level);
		$criteria->compare('title', $this->title, true);
		$criteria->compare('title_tree', $this->title_tree, true);
		$criteria->compare('alias', $this->alias, true);
		$criteria->compare('alias_en', $this->alias_en, true);
		$criteria->compare('description', $this->description, true);
		$criteria->compare('position', $this->position);
		$criteria->compare('ordering', $this->ordering);
		$criteria->compare('language', $this->language, true);
		$criteria->compare('translate_key', $this->translate_key, true);
		$criteria->compare('created', $this->created, true);
		$criteria->compare('created_by', $this->created_by);
		$criteria->compare('modified', $this->modified, true);
		$criteria->compare('modified_by', $this->modified_by);
		$criteria->compare('published', $this->published);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}