<?php

/**
 * This is the model base class for the table "shop_category".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "ShopCategoryModel".
 *
 * Columns in table "shop_category" available as properties of the model,
 * and there are no model relations.
 *
 * @property integer $category_id
 * @property integer $parent_id
 * @property string $title
 * @property string $alias
 * @property string $title_tree
 * @property string $description
 * @property string $language
 * @property integer $position
 * @property integer $ordering
 * @property integer $level
 * @property integer $published
 * @property string $update_time
 *
 */
abstract class BaseShopCategoryModel extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'shop_category';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'ShopCategoryModel|ShopCategoryModels', $n);
	}

	public static function representingColumn() {
		return 'title';
	}

	public function rules() {
		return array(
			array('title', 'required'),
			array('parent_id, position, ordering, level, published', 'numerical', 'integerOnly'=>true),
			array('title, language', 'length', 'max'=>45),
			array('alias, title_tree', 'length', 'max'=>255),
			array('description, update_time', 'safe'),
			array('parent_id, alias, title_tree, description, language, position, ordering, level, published, update_time', 'default', 'setOnEmpty' => true, 'value' => null),
			array('category_id, parent_id, title, alias, title_tree, description, language, position, ordering, level, published, update_time', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'category_id' => Yii::t('app', 'Category'),
			'parent_id' => Yii::t('app', 'Parent'),
			'title' => Yii::t('app', 'Title'),
			'alias' => Yii::t('app', 'Alias'),
			'title_tree' => Yii::t('app', 'Title Tree'),
			'description' => Yii::t('app', 'Description'),
			'language' => Yii::t('app', 'Language'),
			'position' => Yii::t('app', 'Position'),
			'ordering' => Yii::t('app', 'Ordering'),
			'level' => Yii::t('app', 'Level'),
			'published' => Yii::t('app', 'Published'),
			'update_time' => Yii::t('app', 'Update Time'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('category_id', $this->category_id);
		$criteria->compare('parent_id', $this->parent_id);
		$criteria->compare('title', $this->title, true);
		$criteria->compare('alias', $this->alias, true);
		$criteria->compare('title_tree', $this->title_tree, true);
		$criteria->compare('description', $this->description, true);
		$criteria->compare('language', $this->language, true);
		$criteria->compare('position', $this->position);
		$criteria->compare('ordering', $this->ordering);
		$criteria->compare('level', $this->level);
		$criteria->compare('published', $this->published);
		$criteria->compare('update_time', $this->update_time, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}