<?php

/**
 * This is the model base class for the table "{{content_files}}".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "ContentFilesModel".
 *
 * Columns in table "{{content_files}}" available as properties of the model,
 * and there are no model relations.
 *
 * @property integer $id
 * @property integer $content_id
 * @property integer $file_id
 * @property integer $content_type
 *
 */
abstract class BaseContentFilesModel extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return '{{content_files}}';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'ContentFilesModel|ContentFilesModels', $n);
	}

	public static function representingColumn() {
		return 'id';
	}

	public function rules() {
		return array(
			array('content_id, file_id', 'required'),
			array('content_id, file_id, content_type', 'numerical', 'integerOnly'=>true),
			array('content_type', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, content_id, file_id, content_type', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'content_id' => Yii::t('app', 'Content'),
			'file_id' => Yii::t('app', 'File'),
			'content_type' => Yii::t('app', 'Content Type'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('content_id', $this->content_id);
		$criteria->compare('file_id', $this->file_id);
		$criteria->compare('content_type', $this->content_type);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}